### ISSUE TITLE
Tutorial1/Example7 crash 

### ISSUE THREAD

**Issue by petermao** [dacelib/dace#30] opened 2021-12-14 16:50 UTC
Example7 crashes at [line 37](https://github.com/dacelib/dace/blob/d12a941d622a93fa9d36a7781d13d49651db54a5/Tutorials/Tutorial1/Example7.cpp#L37).

```
libc++abi.dylib: terminating with uncaught exception of type DACE::DACEException: daceRoot: Zero-th root does not exist (ID: 645)
Abort trap: 6
```

I'm running on OSX.  `libc++abi.dylib` is version 902.0.0 (according to otool).

It runs w/o the crash if I add 1e-9 to `x[0]` at [line 28](https://github.com/dacelib/dace/blob/d12a941d622a93fa9d36a7781d13d49651db54a5/Tutorials/Tutorial1/Example7.cpp#L28), but the coefficients are almost certainly wrong.
```
Evaluate sombrero function

z
     I  COEFFICIENT              ORDER EXPONENTS
     1    9.9999999999999989e-01   0   0  0
     2    5.9104644775390618e+01   2   2  0
     3    1.3743895347200000e+11   3   1  2
     4    1.4167642029942726e+10   3   3  0
     5    7.3786976294838206e+19   4   2  2
     6   -3.4437640265295577e+19   4   4  0
     7    7.9228162514264338e+28   5   3  2
     8   -3.9349336029542597e+28   5   5  0
     9    5.3169119831396635e+37   6   0  6
    10   -2.0416942015256308e+39   6   2  4
    11    1.5312706511442231e+39   6   4  2
    12   -2.1536402429816355e+38   6   6  0
    13   -3.1056909793281687e+48   7   3  4
    14    6.3940696633227003e+47   7   5  2
    15   -2.1264739034457924e+47   7   7  0
    16    6.1299821634635554e+54   8   0  8
    17    1.9615942923083377e+56   8   2  6
    18    3.9231885846166755e+56   8   4  4
    19    9.8079714615416887e+55   8   6  2
    20    3.3681793960999757e+56   8   8  0
    21    6.8452989584562171e+65   9   1  8
    22   -1.0109980000181490e+67   9   3  6
    23    1.3479973333575320e+67   9   5  4
    24   -3.6859302083995015e+66   9   7  2
    25    3.5999976382425530e+65   9   9  0
    26    3.5336941295567687e+73  10   0 10
    27   -4.5231284858326639e+75  10   2  8
    28    5.4277541829991967e+75  10   4  6
    29    1.0855508365998393e+76  10   6  4
    30    2.0919469246976070e+75  10   8  2
    31   -3.7425681696996680e+74  10  10  0
```

**Comment by petermao** [comment] 2021-12-14 22:15
Ah... looking at Tutorial2/1Basics-Ex.cpp, it appears that this is a known limitation.

**Comment by mmassari1974** [comment] 2021-12-17 14:33
Closing the issue, as it is not a bug but the expected behaviour of the library when evaluated in singular points.

**Closed by mmassari1974** 2021-12-17 14:33 UTC
